### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jmcrey** [Samko1928/intro-data-capstone-biodiversity#2]
### Criteria 1: Presentation / Analysis Document
* _Score Level:_ 3/4
* _Comment(s):_ Most of the requirements are met for the analysis document: 1) there are data observation slides using matplotlib plots, 2) there is a slide for hypothesis testing and results, and 3) there is a conclusion slide for each section. However, the document does not contain a centralized conclusion / recommendation slide, nor does it have an overview slide stating the objective of analysis. It is important for a presentation to contain both an overview and recommendation slides because they remind the reader as to why the presentation is important, and they provide all conclusions from the study in a succinct manner. Otherwise, this presentation was very detailed and contained all results from the study. Nice job!
 
### Criteria 2: Code Accuracy
* _Score Level:_ 4/4
* _Comment(s):_  All of the code looks great! It follows Python's best practices, calculates all values correctly, and makes great use of all the imported libraries. Nice job!
 
### Criteria 3: Understanding Hypothesis Testing and Interpreting the P-Value
* _Score Level:_ 4/4
* _Comment(s):_ The hypothesis testing in the presentation was excellent! It very clearly stated the hypothesis, ran the proper testing, stated whether the hypothesis was accepted or rejected, and interpreted this outcome accurately. Very nice job!
 
### Criteria 4: Ability to Interpret the Objective & Outcome of the Analysis in Business Context
* _Score Level:_ 2/4
* _Comment(s):_ Because there is no clear objective nor recommendation / conclusion slide, it does not appear that the requirements were met. However, the presentation did have recommendations and conclusions throughout, so it seems that the recommendations (albeit not centralized) do meet the requirements for this project.
 
### Overall Score: 13/16

Overall, this was a good project! The biggest thing I noticed is that there was no objective nor a centralized recommendation / conclusion slide. These slides are important to remind the viewer why this presentation is important to them, and give them a centralized place to view what the outcomes of the study were. However, the presentation was still very detailed, contained all relevant information, and all the results were accurate and based on evidence. 

Nice job with this project!

**Comment by Samko1928** [comment]
Thank you for your review and the feedback!
First, is it ok to ask if this score means that I passed? :-)
Second, I am a bit disappointed to loose a point on the code because the instructions clearly stated "If you completed this project on codecademy.com rather than on your own computer, please create a readme.txt file that says “Completed Code in the Learning Environment”". I went ahead and attached the full code from the "learning environment" here. 
[script.txt](https://github.com/Samko1928/intro-data-capstone-biodiversity/files/3124343/script.txt)
Will this help to get a point back?
I agree that my document lacks a centralized conclusion / recommendation slide. Overall, if I already had passed, I won't change anything in the document but definitely will take heed for my next assignments.
Thanks again!
Sam Golant

**Comment by Samko1928** [comment]
@jmcrey
Thank you for your review and the feedback!
First, is it ok to ask if this score means that I passed? :-)
Second, I am a bit disappointed to loose a point on the code because the instructions clearly stated "If you completed this project on codecademy.com rather than on your own computer, please create a readme.txt file that says “Completed Code in the Learning Environment”". I went ahead and attached the full code from the "learning environment" here.
script.txt
Will this help to get a point back?
I agree that my document lacks a centralized conclusion / recommendation slide. Overall, if I already had passed, I won't change anything in the document but definitely will take heed for my next assignments.
Thanks again!
Sam Golant

**Comment by jmcrey** [comment]
@Samko1928 I sincerely apologize for the delay in response. I have reviewed your code and all of it looks great! It is efficient, to the point and correctly calculates all values necessary. I have updated the point score to reflect this new addition.

Also, I do believe you have passed the intensive. If you do not hear back about a certificate of completion soon, please let me know and I will reach out to those who may be able to assist you. 

Thank you for your patience and if you have any further questions, please let me know!

Cheers,
Jeremiah

**Comment by Samko1928** [comment]
@jmcrey Thank you so much, Jeremiah!!
